//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHITIET_PHIEUNHAPHANG
    {
        public int IDCTPN { get; set; }
        public string IDPN { get; set; }
        public string IDHH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string GHICHU { get; set; }
    
        public virtual tb_HANGHOA tb_HANGHOA { get; set; }
        public virtual tb_PHIEUNHAPHANG tb_PHIEUNHAPHANG { get; set; }
    }
}
