//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHITIET_PHIEUBANHANG
    {
        public int IDCTPB { get; set; }
        public string IDPB { get; set; }
        public string IDHH { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<double> QUYDOI { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual tb_HANGHOA tb_HANGHOA { get; set; }
        public virtual tb_PHIEUBANHANG tb_PHIEUBANHANG { get; set; }
    }
}
