//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GIA
    {
        public int IDGIA { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<double> QUYDOI { get; set; }
        public Nullable<double> GIANHAP { get; set; }
        public Nullable<double> GIABANLE { get; set; }
        public Nullable<double> GIABANSI { get; set; }
        public string IDHH { get; set; }
    
        public virtual tb_HANGHOA tb_HANGHOA { get; set; }
    }
}
