//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HANGHOA()
        {
            this.tb_CHITIET_PHIEUBANHANG = new HashSet<tb_CHITIET_PHIEUBANHANG>();
            this.tb_CHITIET_PHIEUNHAPHANG = new HashSet<tb_CHITIET_PHIEUNHAPHANG>();
            this.tb_GIA = new HashSet<tb_GIA>();
        }
    
        public string IDHH { get; set; }
        public string TENHH { get; set; }
        public string MaVach { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> IDLOAI { get; set; }
        public Nullable<double> DINHMUCTON { get; set; }
        public Nullable<double> TONKHO { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CHITIET_PHIEUBANHANG> tb_CHITIET_PHIEUBANHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CHITIET_PHIEUNHAPHANG> tb_CHITIET_PHIEUNHAPHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GIA> tb_GIA { get; set; }
        public virtual tb_LOAIHANGHOA tb_LOAIHANGHOA { get; set; }
    }
}
