//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PHANQUYEN
    {
        public int ID { get; set; }
        public Nullable<int> IDNHOM { get; set; }
        public string FUNC_CODE { get; set; }
        public Nullable<bool> SHOW { get; set; }
        public Nullable<bool> ADD { get; set; }
        public Nullable<bool> UPDATE { get; set; }
        public Nullable<bool> DELETE { get; set; }
        public Nullable<bool> PRINT { get; set; }
    
        public virtual tb_CHUCNANG tb_CHUCNANG { get; set; }
        public virtual tb_NHOM tb_NHOM { get; set; }
    }
}
