//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PHIEUTHU
    {
        public string IDPT { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public string IDKH { get; set; }
        public string IDNV { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<double> SOTIEN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<double> CONGNOCU { get; set; }
        public Nullable<double> CONGNOMOI { get; set; }
    
        public virtual tb_KHACHHANG tb_KHACHHANG { get; set; }
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
        public virtual tb_USER tb_USER { get; set; }
    }
}
